### ISSUE TITLE
Error: Uncaught (in promise) Url: https://localhost:/isAuthenticated

### ISSUE THREAD

**Issue by arturoaviles** [LivePersonInc/lp-demo-app-connector-api#2]
Steps to reproduce:

1. Clone the project
2. Create the image docker build -t demo-connector-app .
3. Run the image docker run -p 8282:8282 -d demo-connector-app
(After this command, You need to wait 1 or 2 minutes till be able to open the app in a browser)
4. Open http://localhost:8282 in your browser.

Please check the image:

![Screenshot from 2020-01-15 23-25-33](https://user-images.githubusercontent.com/2120957/72496149-5ec60000-37ee-11ea-8d3d-3b5a43729915.png)

**Comment by eplazaso** [comment]
Hi, I have changed the Dockerfile. Now it should work, you can repeat the steps ( don't forget to 'kill' the demo-connector-app old running  docker container before)
